import { X } from "lucide-react";
import { useEffect, useRef } from "react";
import Hls from "hls.js";

function buildSrc(movie) {
  const vid = (movie.video_id || movie.video_url || "").trim();
    const type = movie.type || "direct";
      if (!vid) return null;

        if (vid.includes("kaltura.com")) return vid;

          if (type === "kaltura") {
              const parts = vid.split("/");
                  if (parts.length >= 3) {
                        const partnerId = parts[0], uiconfId = parts[1], entryId = parts[2];
                              return `https://cdnapisec.kaltura.com/p/${partnerId}/embedPlaykitJs/uiconf_id/${uiconfId}?iframeembed=true&entry_id=${entryId}`;
                                  }
                                      return null;
                                        }

                                          if (type === "youtube" || vid.includes("youtube.com") || vid.includes("youtu.be")) {
                                              const m = vid.match(/(?:v=|youtu\.be\/)([^&/?]+)/);
                                                  const id = m ? m[1] : vid;
                                                      return `https://www.youtube.com/embed/${id}?autoplay=1`;
                                                        }

                                                          if (type === "drive" || vid.includes("drive.google.com")) {
                                                              const m = vid.match(/\/d\/([^/?]+)/);
                                                                  const id = m ? m[1] : vid;
                                                                      return `https://drive.google.com/file/d/${id}/preview`;
                                                                        }

                                                                          if (type === "vimeo" || vid.includes("vimeo.com")) {
                                                                              const m = vid.match(/vimeo\.com\/(\d+)/);
                                                                                  const id = m ? m[1] : vid;
                                                                                      return `https://player.vimeo.com/video/${id}?autoplay=1`;
                                                                                        }

                                                                                          if (type === "dailymotion" || vid.includes("dailymotion.com") || vid.includes("dai.ly")) {
                                                                                              const m = vid.match(/(?:video\/|dai\.ly\/)([a-zA-Z0-9]+)/);
                                                                                                  const id = m ? m[1] : vid;
                                                                                                      return `https://www.dailymotion.com/embed/video/${id}?autoplay=1`;
                                                                                                        }

                                                                                                          if (type === "streamable" || vid.includes("streamable.com")) {
                                                                                                              const m = vid.match(/streamable\.com\/([a-zA-Z0-9]+)/);
                                                                                                                  const id = m ? m[1] : vid;
                                                                                                                      return `https://streamable.com/e/${id}?autoplay=1`;
                                                                                                                        }

                                                                                                                          if (type === "rumble" || vid.includes("rumble.com")) {
                                                                                                                              const m = vid.match(/(?:embed\/|video\/)([a-zA-Z0-9]+)/);
                                                                                                                                  const id = m ? m[1] : vid;
                                                                                                                                      return `https://rumble.com/embed/${id}/`;
                                                                                                                                        }

                                                                                                                                          if (type === "archive" || vid.includes("archive.org")) {
                                                                                                                                              const m = vid.match(/archive\.org\/(?:embed|details)\/([^/?]+)/);
                                                                                                                                                  const id = m ? m[1] : vid;
                                                                                                                                                      return `https://archive.org/embed/${id}`;
                                                                                                                                                        }

                                                                                                                                                          if (type === "kan" || vid.includes("kan.org.il")) {
                                                                                                                                                              return `https://www.kan.org.il/General/Embed.aspx?id=${vid}`;
                                                                                                                                                                }

                                                                                                                                                                  if (type === "okru" || vid.includes("ok.ru")) {
                                                                                                                                                                      const m = vid.match(/ok\.ru\/video\/(\d+)/);
                                                                                                                                                                          const id = m ? m[1] : vid;
                                                                                                                                                                              return `https://ok.ru/videoembed/${id}`;
                                                                                                                                                                                }

                                                                                                                                                                                  if (type === "telegram" || vid.includes("t.me")) {
                                                                                                                                                                                      const id = vid.replace(/.*t\.me\//, "");
                                                                                                                                                                                          return `https://t.me/${id}?embed=1&mode=tme`;
                                                                                                                                                                                            }

                                                                                                                                                                                              if (type === "jellyfin") {
                                                                                                                                                                                                  const server = (movie.jellyfin_server || "").replace(/\/$/, "");
                                                                                                                                                                                                      const apiKey = movie.jellyfin_api_key || "";
                                                                                                                                                                                                          if (server && vid) return `${server}/web/index.html#!/video?id=${vid}&serverId=&api_key=${apiKey}`;
                                                                                                                                                                                                              return null;
                                                                                                                                                                                                                }

                                                                                                                                                                                                                  if (type === "cloudinary") {
                                                                                                                                                                                                                      const cloud = movie.cloudinary_cloud_name || "";
                                                                                                                                                                                                                          return cloud ? `https://res.cloudinary.com/${cloud}/video/upload/${vid}` : null;
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                              return vid.startsWith("http") ? vid : null;
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                              function isHlsUrl(src) {
                                                                                                                                                                                                                                if (!src) return false;
                                                                                                                                                                                                                                  return src.includes(".m3u8") || src.includes("Manifest.ism");
                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                  function isIframeUrl(src, type) {
                                                                                                                                                                                                                                    if (!src) return false;
                                                                                                                                                                                                                                      const iframeTypes = ["youtube", "drive", "vimeo", "dailymotion", "streamable",
                                                                                                                                                                                                                                          "rumble", "archive", "kan", "okru", "telegram", "kaltura", "jellyfin"];
                                                                                                                                                                                                                                            if (iframeTypes.includes(type)) return true;
                                                                                                                                                                                                                                              const iframeDomains = ["youtube.com", "youtu.be", "drive.google.com", "vimeo.com",
                                                                                                                                                                                                                                                  "dailymotion.com", "streamable.com", "rumble.com", "archive.org",
                                                                                                                                                                                                                                                      "kan.org.il", "ok.ru", "t.me", "kaltura.com"];
                                                                                                                                                                                                                                                        return iframeDomains.some(d => src.includes(d));
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                        function HlsPlayer({ src }) {
                                                                                                                                                                                                                                                          const videoRef = useRef(null);

                                                                                                                                                                                                                                                            useEffect(() => {
                                                                                                                                                                                                                                                                const video = videoRef.current;
                                                                                                                                                                                                                                                                    if (!video || !src) return;
                                                                                                                                                                                                                                                                        if (video.canPlayType("application/vnd.apple.mpegurl")) {
                                                                                                                                                                                                                                                                              video.src = src;
                                                                                                                                                                                                                                                                                    video.play().catch(() => {});
                                                                                                                                                                                                                                                                                        } else if (Hls.isSupported()) {
                                                                                                                                                                                                                                                                                              const hls = new Hls({ enableWorker: true, lowLatencyMode: false });
                                                                                                                                                                                                                                                                                                    hls.loadSource(src);
                                                                                                                                                                                                                                                                                                          hls.attachMedia(video);
                                                                                                                                                                                                                                                                                                                hls.on(Hls.Events.MANIFEST_PARSED, () => video.play().catch(() => {}));
                                                                                                                                                                                                                                                                                                                      return () => hls.destroy();
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                            }, [src]);

                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                  <video
                                                                                                                                                                                                                                                                                                                                        ref={videoRef}
                                                                                                                                                                                                                                                                                                                                              controls
                                                                                                                                                                                                                                                                                                                                                    autoPlay
                                                                                                                                                                                                                                                                                                                                                          playsInline
                                                                                                                                                                                                                                                                                                                                                                controlsList="nodownload"
                                                                                                                                                                                                                                                                                                                                                                      style={{ flex: 1, width: "100%", background: "#000" }}
                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                            export default function CustomVideoPlayer({ movie, onClose }) {
                                                                                                                                                                                                                                                                                                                                                                              const src = buildSrc(movie);
                                                                                                                                                                                                                                                                                                                                                                                const type = movie.type || "direct";
                                                                                                                                                                                                                                                                                                                                                                                  const hlsVideo = isHlsUrl(src);
                                                                                                                                                                                                                                                                                                                                                                                    const useIframe = !hlsVideo && isIframeUrl(src, type);

                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                          <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                position: "fixed", inset: 0, background: "#000", zIndex: 9999,
                                                                                                                                                                                                                                                                                                                                                                                                      display: "flex", flexDirection: "column"
                                                                                                                                                                                                                                                                                                                                                                                                          }}>

                                                                                                                                                                                                                                                                                                                                                                                                                {/* כפתור סגירה */}
                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                position: "absolute", top: 15, right: 15, zIndex: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: "rgba(255,255,255,0.15)", border: "none", color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "50%", width: 44, height: 44,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "flex", alignItems: "center", justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: "pointer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <X size={24} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* כותרת */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#888", fontSize: 13, margin: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "14px 60px 10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textAlign: "center", fontFamily: "Arial", flexShrink: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {movie.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* נגן */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {!src ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  flex: 1, display: "flex", alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            justifyContent: "center", color: "#555", fontSize: 15, fontFamily: "Arial"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              אין קישור וידאו זמין
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : hlsVideo ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <HlsPlayer src={src} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : useIframe ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <iframe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            src={src}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ flex: 1, width: "100%", border: "none" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                allowFullScreen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          allow="autoplay; encrypted-media; picture-in-picture"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <video
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          src={src}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    controls
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              autoPlay
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        playsInline
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  controlsList="nodownload"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ flex: 1, width: "100%", background: "#000" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                